# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_simulator.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(289, 281)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.hexp_dspin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.hexp_dspin.setMaximum(1.0)
        self.hexp_dspin.setSingleStep(0.01)
        self.hexp_dspin.setObjectName("hexp_dspin")
        self.gridLayout.addWidget(self.hexp_dspin, 2, 1, 1, 1)
        self.hdelta_dspin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.hdelta_dspin.setMaximum(1.0)
        self.hdelta_dspin.setSingleStep(0.01)
        self.hdelta_dspin.setObjectName("hdelta_dspin")
        self.gridLayout.addWidget(self.hdelta_dspin, 2, 2, 1, 1)
        self.hvol_dspin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.hvol_dspin.setMaximum(1.0)
        self.hvol_dspin.setSingleStep(0.01)
        self.hvol_dspin.setObjectName("hvol_dspin")
        self.gridLayout.addWidget(self.hvol_dspin, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.aexp_dspin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.aexp_dspin.setMaximum(1.0)
        self.aexp_dspin.setSingleStep(0.01)
        self.aexp_dspin.setObjectName("aexp_dspin")
        self.gridLayout.addWidget(self.aexp_dspin, 3, 1, 1, 1)
        self.adel_dspin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.adel_dspin.setMaximum(1.0)
        self.adel_dspin.setSingleStep(0.01)
        self.adel_dspin.setObjectName("adel_dspin")
        self.gridLayout.addWidget(self.adel_dspin, 3, 2, 1, 1)
        self.avol_dspin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.avol_dspin.setMaximum(1.0)
        self.avol_dspin.setSingleStep(0.01)
        self.avol_dspin.setObjectName("avol_dspin")
        self.gridLayout.addWidget(self.avol_dspin, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 3)
        self.freq_slider = QtWidgets.QSlider(self.centralwidget)
        self.freq_slider.setMinimum(1)
        self.freq_slider.setMaximum(100)
        self.freq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.freq_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.freq_slider.setTickInterval(5)
        self.freq_slider.setObjectName("freq_slider")
        self.gridLayout.addWidget(self.freq_slider, 5, 0, 1, 4)
        self.pb_start = QtWidgets.QPushButton(self.centralwidget)
        self.pb_start.setObjectName("pb_start")
        self.gridLayout.addWidget(self.pb_start, 6, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 289, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Queue"))
        self.label_4.setText(_translate("MainWindow", "Expected"))
        self.label_5.setText(_translate("MainWindow", "Delta"))
        self.label_6.setText(_translate("MainWindow", "Volatility"))
        self.label.setText(_translate("MainWindow", "Home"))
        self.label_2.setText(_translate("MainWindow", "Away"))
        self.label_7.setText(_translate("MainWindow", "Update frequency (per second)"))
        self.pb_start.setText(_translate("MainWindow", "Start"))


